# Generated by Django 5.1.2 on 2024-11-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('goods', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('inv_value', models.DecimalField(decimal_places=3, max_digits=15)),
                ('forwarder', models.CharField(max_length=100)),
                ('incoterm', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('bl_awb_no', models.CharField(max_length=100)),
                ('bl_awb_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etd', models.DateField()),
                ('eta', models.DateField()),
                ('kind_of', models.CharField(max_length=50)),
                ('container_no', models.CharField(max_length=100)),
                ('nop', models.CharField(max_length=100)),
                ('vsl', models.CharField(max_length=100)),
                ('boe_no', models.CharField(max_length=100)),
                ('boe_date', models.DateField()),
                ('ex_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dutypaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boe_frt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boe_exw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
