# Generated by Django 5.1.2 on 2024-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('bank', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50)),
            ],
        ),
    ]
