# Generated by Django 5.1.2 on 2024-11-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('part_description', models.TextField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('EA', 'Each'), ('KGS', 'Kilograms'), ('LTRS', 'Liters')], max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('bcd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sws', models.DecimalField(decimal_places=4, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cth', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier.supplier')),
            ],
        ),
    ]
